### ISSUE TITLE
Any chance of a NuGet package....

### ISSUE THREAD

**Issue by natiki** [thiagotts/parilis#3]
Hi,

Any chance we can get this as a NuGet package?

**Comment by thiagotts** [comment]
Hi,

Since I wrote this tool, it's being used in a couple of projects inside a single organization, so we haven't faced the need to make it available as a NuGet package yet. But yes, it is possible to do it and I'm adding it to the project's todo list.

**Comment by natiki** [comment]
Hi,

This is a nice to have and can definitely be put at the bottom of the list.

**Comment by thiagotts** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;yN3u2b7l&#x2F;3-make-it-available-as-nuget-package"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Make it available as NuGet package</a>

**Comment by reboucaslinhares** [comment]
Version 0.4 available o nuget.org.
At package manager console window, select the project that you want to install and type:
```
Install-Package Parilis.SqlServer
```
