### ISSUE TITLE
Add a progress event....

### ISSUE THREAD

**Issue by natiki** [thiagotts/parilis#4]
Hi,

Calling

``` c#
   var database1 = new DatabaseDescription(connectionInfo1);
```

obviously starts the process, and on a large database this provides no feedback that "something is happening". It would be nice to get some form of notification event periodically so that a GUI could be updated, etc.

**Comment by thiagotts** [comment]
Thanks for the suggestion! I just added this to the project's todo list.

**Comment by thiagotts** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;CituSk0F&#x2F;2-provide-feedback-for-progress-events"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Provide feedback for progress events</a>

**Comment by reboucaslinhares** [comment]
You can now register an lambda or a delegate on OnProgress event of a Parilis object and retrieve the current percentual and a message that describes the last action executed.
Something like (lambda mode):

```cs
var parilis = new Parilis(actualDescription, referenceDescription);
parilis.OnProgress += (percentualProgress, message) => {
   //percentualProgress is a double
   view.UpdateProgress(percentualProgress, message);
 };
parilis.Run();
```
